/**
 * United States shops for the US dry run (docs/INTERNATIONAL-PLAN.md, Phase 1,
 * step one). Nothing here is published: the region crawl
 * (.github/workflows/catalogue-us.yml) reads these shops and writes
 * data/regions/us/ only, and no page reads that folder yet.
 *
 * Every shop was read on 2026-10-09 as PriceSniffsBot and nothing else,
 * robots.txt first (docs/DECISIONS.md D23), from the shortlist in
 * docs/RETAILER-CANDIDATES-USA-INDIA-2026-10-09.md. For each Shopify shop the
 * home page's `Shopify.currency` and `/meta.json` were read: all twelve said
 * USD at rate 1.0, settlement USD, market country US, which is a dollar price
 * list kept in dollars, not a conversion. The two non Shopify shops state
 * `priceCurrency` USD in each product page's JSON-LD.
 *
 * Delivery is standard delivery only, read off the shop's own page with the
 * sentence quoted. Where the page states only a free threshold, `standard`
 * stays null (not established, never zero). Sales tax is never estimated: it
 * depends on the state and the locality, so the honest note is the plan's
 * label (`US_TAX_NOTE`).
 *
 * No affiliate field, no photo field: see src/types/regionRetailer.ts.
 */
import { US_TAX_NOTE, type RegionRetailer } from '../types/regionRetailer.js';

const CHECKED = '2026-10-09';

/** What a Shopify shop said about its currency on 2026-10-09, as the bot. */
const SHOPIFY_USD = 'Shopify.currency {"active":"USD","rate":"1.0"}, /meta.json currency USD, Shopify.country US';

/** Gifts with purchase, sample pickers and loyalty rewards, not things to buy on their own. */
const NOT_FOR_SALE_TYPES = ['Free Gift', 'sample-picker', 'Passport Reward', 'Perfume Sample', 'Gift With Purchase', 'GWP'] as const;

/**
 * Perfumania, Fragrance Outlet and Fragrance Market answer /products.json with
 * the same products in the same order (page one of each, 2026-10-09: Lattafa
 * Ana Abiyed Coral, Pink Blush Shams Al Emarat Khususi, Versace Dylan Blush
 * Pink) and the same ten digit sku numbering (1000005263 is one bottle at all
 * three). Counted as one source in the "two or more shops" measure.
 */
const SAME_CATALOGUE_PERFUMANIA = 'perfumania-catalogue';

function unverified(notes: string): RegionRetailer['delivery'] {
  return { standard: null, freeOver: null, estimatedDays: null, verifiedAt: CHECKED, confidence: 'unverified', notes };
}

export const US_RETAILERS: readonly RegionRetailer[] = [
  {
    id: 'perfumania',
    name: 'Perfumania',
    region: 'US',
    currency: 'USD',
    domain: 'perfumania.com',
    homepage: 'https://perfumania.com/',
    tiers: ['designer', 'mideast'],
    catalogueGroup: SAME_CATALOGUE_PERFUMANIA,
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: {
      standard: 6.95,
      freeOver: 59,
      freeOverInclusive: true,
      estimatedDays: [4, 8],
      verifiedAt: CHECKED,
      confidence: 'confirmed',
      source: {
        url: 'https://perfumania.com/pages/shipping-policy',
        quote: 'Standard Ground Shipping Regular 4-8 business days $6.95 ... To qualify for free ground shipping, the order sub-total must be $59 or more after all discounts are applied.',
        readAt: CHECKED,
      },
      notes: 'Free shipping only to the contiguous United States; Alaska and Hawaii pay a $5.99 surcharge. /policies/ is disallowed by its robots.txt, so the page under /pages/ was read.',
    },
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}.`,
  },
  {
    id: 'jomashop',
    name: 'Jomashop',
    region: 'US',
    currency: 'USD',
    domain: 'www.jomashop.com',
    homepage: 'https://www.jomashop.com/',
    tiers: ['designer', 'niche'],
    enabled: false,
    blockedReason:
      'Its product pages carry no price in their markup: a fragrance page read on 2026-10-09 (intenso-men-edp-spray-4-2-oz-3423473020820.html, 81 KB) has no JSON-LD, no microdata and no price meta; the price is drawn by its script. /products.json is 404. Its 38 sitemaps are about 18 MB each and mostly watches. Needs a route that reads a price the page states; the free local render tier is the candidate, after the dry run.',
    route: {
      kind: 'sitemap',
      sitemapRoute: {
        roots: ['https://www.jomashop.com/sitemap.xml'],
        product: '^https://www\\.jomashop\\.com/[^/]*(?:edp|edt|eau-de|parfum|perfume|cologne)[^/]*\\.html$',
        maxSitemaps: 4,
        requireGbp: true,
      },
    },
    minRequestGapMs: 2000,
    delivery: unverified('Its help pages refused our fetch on 2026-10-09 (docs/RETAILER-CANDIDATES-USA-INDIA-2026-10-09.md).'),
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200 (720 B); home 200; /products.json 404; product page without a stated price.`,
  },
  {
    id: 'luckyscent',
    name: 'Luckyscent',
    region: 'US',
    currency: 'USD',
    domain: 'www.luckyscent.com',
    homepage: 'https://www.luckyscent.com/',
    tiers: ['niche'],
    // A perfumery: its product sitemaps list perfume, with candles, incense and
    // body care left out by the route's `exclude`. Its titles name the scent and
    // the size only ("Cherry Ink - 50ml", Lorenzo Pazzaglia).
    fragranceOnlyCatalogue: true,
    enabled: true,
    route: {
      kind: 'sitemap',
      sitemapRoute: {
        roots: ['https://www.luckyscent.com/sitemap.xml'],
        follow: '/sitemap/products/\\d+\\.xml$',
        product: '^https://www\\.luckyscent\\.com/products/[^/?#]+$',
        exclude: '(?:candle|diffuser|incense|soap|lotion|body-wash|shower|gift-card|sample-set|discovery)',
        maxSitemaps: 40,
        requireGbp: true,
      },
    },
    minRequestGapMs: 1500,
    delivery: unverified('Its delivery terms sit under /policies/, which its robots.txt disallows; not read.'),
    taxNote: US_TAX_NOTE,
    checked:
      `${CHECKED}: robots.txt 200; home 200; /products.json 404; sitemap index of 34 product sitemaps (about 143 products each); ` +
      'three product pages read, each with one JSON-LD Product, offers in priceCurrency USD (Cherry Ink 50ml $175). ' +
      'Its JSON-LD repeats one gtin on different perfumes (8050628980071 on Cherry Ink and Van Extasyx), which the region build refuses as an identity.',
  },
  {
    id: 'aedes',
    name: 'Aedes',
    region: 'US',
    currency: 'USD',
    domain: 'www.aedes.com',
    homepage: 'https://www.aedes.com/',
    tiers: ['niche'],
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: unverified('/policies/ is disallowed by its robots.txt and no /pages/ shipping page answered.'),
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}.`,
  },
  {
    id: 'twisted-lily',
    name: 'Twisted Lily',
    region: 'US',
    currency: 'USD',
    domain: 'twistedlily.com',
    homepage: 'https://twistedlily.com/',
    tiers: ['niche'],
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: unverified('Its shipping policy (twistedlily.com/policies/shipping-policy, read 2026-10-09) gives Canada and international rates only; no domestic rate found.'),
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}. Its "Free Gift" product type is a gift with purchase and is dropped.`,
  },
  {
    id: 'indigo-perfumery',
    name: 'Indigo Perfumery',
    region: 'US',
    currency: 'USD',
    domain: 'indigoperfumery.com',
    homepage: 'https://indigoperfumery.com/',
    tiers: ['niche'],
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: unverified('No shipping page answered; its FAQ states no standard rate.'),
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}.`,
  },
  {
    id: 'bluemercury',
    name: 'Bluemercury',
    region: 'US',
    currency: 'USD',
    domain: 'bluemercury.com',
    homepage: 'https://bluemercury.com/',
    tiers: ['designer', 'niche'],
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: unverified('Its shipping help is drawn by a help centre script; no rate in the markup. /policies/ is disallowed by its robots.txt.'),
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}.`,
  },
  {
    id: 'beautyhabit',
    name: 'Beautyhabit',
    region: 'US',
    currency: 'USD',
    domain: 'www.beautyhabit.com',
    homepage: 'https://www.beautyhabit.com/',
    tiers: ['niche'],
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: {
      standard: 8.95,
      freeOver: 85,
      freeOverInclusive: true,
      estimatedDays: null,
      verifiedAt: CHECKED,
      confidence: 'confirmed',
      source: {
        url: 'https://www.beautyhabit.com/pages/faqs',
        quote: '$8.95 and free shipping options apply only to orders shipped within the contiguous United States. ... Standard Contiguous USA Domestic Ground shipping is free on orders $85* or more.',
        readAt: CHECKED,
      },
      notes: 'Alaska, Hawaii and US territories pay more (USPS only).',
    },
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}.`,
  },
  {
    id: 'ds-and-durga',
    name: 'D.S. & Durga',
    region: 'US',
    currency: 'USD',
    domain: 'www.dsanddurga.com',
    homepage: 'https://www.dsanddurga.com/',
    tiers: ['niche'],
    singleBrandOnly: 'D.S. & Durga',
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: {
      standard: null,
      freeOver: 75,
      freeOverInclusive: false,
      estimatedDays: null,
      verifiedAt: CHECKED,
      confidence: 'confirmed',
      source: {
        url: 'https://www.dsanddurga.com/policies/shipping-policy',
        quote: 'We offer free ground shipping for all continental United States orders over $75 (excludes Puerto Rico, Guam, American Samoa, Alaska, and Hawaii).',
        readAt: CHECKED,
      },
      notes: 'The page states no rate below $75.',
    },
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}.`,
  },
  {
    id: 'imaginary-authors',
    name: 'Imaginary Authors',
    region: 'US',
    currency: 'USD',
    domain: 'imaginaryauthors.com',
    homepage: 'https://imaginaryauthors.com/',
    tiers: ['niche'],
    singleBrandOnly: 'Imaginary Authors',
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: {
      standard: null,
      freeOver: 75,
      freeOverInclusive: false,
      estimatedDays: null,
      verifiedAt: CHECKED,
      confidence: 'confirmed',
      source: {
        url: 'https://imaginaryauthors.com/pages/faqs',
        quote: 'Beyond that, we are happy to offer complimentary shipping within the continental United States on orders exceeding $75.',
        readAt: CHECKED,
      },
      notes: 'The page states no rate below $75.',
    },
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}.`,
  },
  {
    id: 'maison-louis-marie',
    name: 'Maison Louis Marie',
    region: 'US',
    currency: 'USD',
    domain: 'maisonlouismarie.com',
    homepage: 'https://maisonlouismarie.com/',
    tiers: ['niche'],
    singleBrandOnly: 'Maison Louis Marie',
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: {
      standard: null,
      freeOver: 50,
      freeOverInclusive: false,
      estimatedDays: [3, 7],
      verifiedAt: CHECKED,
      confidence: 'confirmed',
      source: {
        url: 'https://maisonlouismarie.com/pages/faqs',
        quote: '(FedEx Ground): 3–7 business days ... We do offer free shipping with FEDEX ground on orders over $50.',
        readAt: CHECKED,
      },
      notes: 'Eau de parfum ships by ground only. The page states no rate below $50.',
    },
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}.`,
  },
  {
    id: 'ellis-brooklyn',
    name: 'Ellis Brooklyn',
    region: 'US',
    currency: 'USD',
    domain: 'www.ellisbrooklyn.com',
    homepage: 'https://www.ellisbrooklyn.com/',
    tiers: ['niche'],
    singleBrandOnly: 'Ellis Brooklyn',
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: {
      standard: 8,
      freeOver: 40,
      freeOverInclusive: false,
      estimatedDays: null,
      verifiedAt: CHECKED,
      confidence: 'confirmed',
      source: {
        url: 'https://www.ellisbrooklyn.com/policies/shipping-policy',
        quote: 'Standard shipping within the continental US is free on any order above $40 (not including 1.5ml Vials). Standard shipping is a flat rate of $8 for all orders (for orders under $40).',
        readAt: CHECKED,
      },
      notes: 'Alaska and Hawaii: $15 flat on orders up to 15 lb.',
    },
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}.`,
  },
  {
    id: 'boy-smells',
    name: 'Boy Smells',
    region: 'US',
    currency: 'USD',
    domain: 'boysmells.com',
    homepage: 'https://boysmells.com/',
    tiers: ['niche'],
    singleBrandOnly: 'Boy Smells',
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: {
      standard: null,
      freeOver: 50,
      freeOverInclusive: false,
      estimatedDays: null,
      verifiedAt: CHECKED,
      confidence: 'confirmed',
      source: {
        url: 'https://boysmells.com/pages/shipping-policy',
        quote: 'Enjoy Free Shipping on All US Orders Over $50',
        readAt: CHECKED,
      },
      notes: 'Read from the banner on its own shipping page; the page states no rate below $50.',
    },
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}. Most of its range is candles.`,
  },
  {
    id: 'sol-de-janeiro',
    name: 'Sol de Janeiro',
    region: 'US',
    currency: 'USD',
    domain: 'soldejaneiro.com',
    homepage: 'https://soldejaneiro.com/',
    tiers: ['designer'],
    singleBrandOnly: 'Sol de Janeiro',
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: {
      standard: 7.5,
      freeOver: 35,
      freeOverInclusive: true,
      estimatedDays: [7, 10],
      verifiedAt: CHECKED,
      confidence: 'confirmed',
      source: {
        url: 'https://soldejaneiro.com/policies/shipping-policy',
        quote: 'USA : We charge a $7.50 flat rate for standard shipping + taxes and free standard shipping on orders of $35 or more within the US.',
        readAt: CHECKED,
      },
      notes: 'Delivered within 7 to 10 business days after processing (1 to 3 business days).',
    },
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}. Mostly body care and mists.`,
  },
  // ── Round 2 (docs/RETAILER-CANDIDATES-US-IN-ROUND2-2026-10-09.md), each route
  // re-checked against its robots.txt as PriceSniffsBot on 2026-10-09 ──
  {
    id: 'beauty-encounter',
    name: 'Beauty Encounter',
    region: 'US',
    currency: 'USD',
    domain: 'beautyencounter.com',
    homepage: 'https://beautyencounter.com/',
    tiers: ['designer', 'niche'],
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    // 475 of 524 variants sampled in round 2 carry a 12 or 13 digit sku.
    skuIsBarcode: true,
    delivery: {
      standard: null,
      freeOver: 50,
      freeOverInclusive: true,
      estimatedDays: null,
      verifiedAt: CHECKED,
      confidence: 'confirmed',
      source: {
        url: 'https://beautyencounter.com/pages/shipping-information',
        quote: 'This offer is only good on purchases of $50 or more shipped within the domestic 48 US states.',
        readAt: CHECKED,
      },
      notes: 'Free Standard Ground on $50 or more to the 48 contiguous states (round 2 noted $35; the page read on 2026-10-09 says $50). No rate below it was found.',
    },
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200 (/products.json allowed; /cart.js and /recommendations/products disallowed); home 200; /products.json 200; ${SHOPIFY_USD}.`,
  },
  {
    id: 'fragrance-outlet',
    name: 'Fragrance Outlet',
    region: 'US',
    currency: 'USD',
    domain: 'www.fragranceoutlet.com',
    homepage: 'https://www.fragranceoutlet.com/',
    tiers: ['designer', 'mideast'],
    catalogueGroup: SAME_CATALOGUE_PERFUMANIA,
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: unverified('Delivery not confirmed: its shipping policy sits under /policies/, which its robots.txt disallows, so it is not read; the home page shows a "Free Shipping" badge with no figure.'),
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200 (/policies/ disallowed, /products.json allowed); home 200; /products.json 200; ${SHOPIFY_USD}.`,
  },
  {
    id: 'fragrance-market',
    name: 'Fragrance Market',
    region: 'US',
    currency: 'USD',
    domain: 'fragrancemarket.com',
    homepage: 'https://fragrancemarket.com/',
    tiers: ['designer', 'mideast'],
    catalogueGroup: SAME_CATALOGUE_PERFUMANIA,
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: {
      standard: null,
      freeOver: 65,
      freeOverInclusive: true,
      estimatedDays: null,
      verifiedAt: CHECKED,
      confidence: 'unverified',
      source: {
        url: 'https://fragrancemarket.com/pages/frequently-asked-questions',
        quote: 'CART ( 0 ) Spend $65.00 more to earn free shipping!',
        readAt: CHECKED,
      },
      notes: 'Read from the empty cart widget on its own page, not from a delivery policy; no standard rate found.',
    },
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200 (Shopify stock); home 200; /products.json 200; ${SHOPIFY_USD}.`,
  },
  {
    id: 'microperfumes',
    name: 'MicroPerfumes',
    region: 'US',
    currency: 'USD',
    domain: 'microperfumes.com',
    homepage: 'https://microperfumes.com/',
    tiers: ['designer', 'niche'],
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    titleMustMatch: '\\bRetail Bottle\\b',
    delivery: {
      standard: null,
      freeOver: 69,
      freeOverInclusive: true,
      estimatedDays: null,
      verifiedAt: CHECKED,
      confidence: 'unverified',
      source: {
        url: 'https://microperfumes.com/',
        quote: 'Free US Shipping $69+',
        readAt: CHECKED,
      },
      notes: 'Delivery not confirmed: read from the home page banner only. Its shipping policy sits under /policies/, which its robots.txt disallows, so it is not read.',
    },
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200 (stock; /policies/ disallowed); home 200; /products.json 200; ${SHOPIFY_USD}. Only "Retail Bottle" products are kept.`,
  },
  {
    id: 'parfums-raffy',
    name: 'Parfums Raffy',
    region: 'US',
    currency: 'USD',
    domain: 'parfumsraffy.com',
    homepage: 'https://parfumsraffy.com/',
    tiers: ['designer', 'niche'],
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    vendorIsShop: true,
    delivery: unverified('Not read by this pass: /pages/shipping redirects to the home page. Round 2 recorded free Standard on $75 or more and $7.95 below from its own page; to be re-read before the beta.'),
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}. Its vendor is always "Parfums Raffy"; the house is in the title.`,
  },
  {
    id: 'ministry-of-scent',
    name: 'Ministry of Scent',
    region: 'US',
    currency: 'USD',
    domain: 'ministryofscent.com',
    homepage: 'https://ministryofscent.com/',
    tiers: ['niche'],
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: [...NOT_FOR_SALE_TYPES, 'Sample Set'],
    delivery: {
      standard: 10,
      freeOver: 75,
      freeOverInclusive: true,
      estimatedDays: null,
      verifiedAt: CHECKED,
      confidence: 'confirmed',
      source: {
        url: 'https://ministryofscent.com/pages/shipping-policy',
        quote: 'Standard shipping Under $75 USPS Ground Advantage* or UPS Ground** $10 Free shipping $75 and over USPS Ground Advantage* or UPS Ground** $0',
        readAt: CHECKED,
      },
      notes: 'Ships from California; sample only orders $6.',
    },
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}.`,
  },
  {
    id: 'la-belle-perfumes',
    name: 'La Belle Perfumes',
    region: 'US',
    currency: 'USD',
    domain: 'labelleperfumes.com',
    homepage: 'https://labelleperfumes.com/',
    tiers: ['designer', 'mideast'],
    enabled: true,
    route: { kind: 'shopify' },
    minRequestGapMs: 1500,
    excludeProductTypes: NOT_FOR_SALE_TYPES,
    delivery: unverified('No shipping page answered at the usual Shopify addresses.'),
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200; home 200; /products.json 200; ${SHOPIFY_USD}. Sells testers and unboxed bottles beside boxed ones.`,
  },
  {
    id: 'ulta',
    name: 'Ulta Beauty',
    region: 'US',
    currency: 'USD',
    domain: 'www.ulta.com',
    homepage: 'https://www.ulta.com/',
    tiers: ['designer', 'niche'],
    enabled: true,
    route: {
      kind: 'sitemap',
      sitemapRoute: {
        roots: ['https://www.ulta.com/sitemap/index.xml'],
        follow: '/sitemap/p(?:-\\d+)?\\.xml$',
        product: '^https://www\\.ulta\\.com/p/[^?#]*(?:eau-de-parfum|eau-de-toilette|eau-de-cologne|parfum|perfume|cologne|extrait)[^?#]*\\?sku=\\d+$',
        exclude: '(?:body|lotion|shower|mist|deodorant|candle|hair|rollerball-set|gift-set|coffret|discovery)',
        maxSitemaps: 32,
        requireGbp: true,
        // The JSON-LD name carries no size ("Eternity Eau de Parfum"); the page's
        // own analytics record of the selected sku does ("product_variant_size":
        // ["3.3 oz"]). Applied only when the page yields one listing.
        titleParts: ['"product_variant_size":\\["(\\d{1,2}(?:\\.\\d{1,2})?\\s?(?:fl\\.?\\s?)?oz|\\d{1,4}(?:\\.\\d)?\\s?ml)"\\]'],
      },
    },
    minRequestGapMs: 2000,
    delivery: unverified('Its shipping help page did not answer the bot (no response) on 2026-10-09; not read.'),
    taxNote: US_TAX_NOTE,
    checked:
      `${CHECKED}: robots.txt 200 (no User-agent: * group, named bots only, so nothing applies to PriceSniffsBot; sitemap/index.xml named); ` +
      'a product page read (1.4 MB), one JSON-LD Product with priceCurrency USD and gtin12 (Calvin Klein Eternity EDP $123, 088300601400).',
  },
  {
    id: 'the-perfume-spot',
    name: 'The Perfume Spot',
    region: 'US',
    currency: 'USD',
    domain: 'theperfumespot.com',
    homepage: 'https://theperfumespot.com/',
    tiers: ['designer', 'niche'],
    enabled: true,
    route: {
      kind: 'sitemap',
      sitemapRoute: {
        // BigCommerce's own product sitemap (listed by its /xmlsitemap.php index;
        // page 2 is 404). robots.txt names no sitemap and disallows only account,
        // cart and search paths. Named directly because the walk follows only
        // children ending .xml.
        roots: ['https://theperfumespot.com/xmlsitemap.php?type=products&page=1'],
        product: '^https://theperfumespot\\.com/[^/?#]+/$',
        exclude: '(?:lotion|shower-gel|deodorant|body-mist|gift-set|candle)',
        maxSitemaps: 1,
        requireGbp: true,
      },
    },
    minRequestGapMs: 2000,
    delivery: {
      standard: null,
      freeOver: 49,
      freeOverInclusive: false,
      estimatedDays: null,
      verifiedAt: CHECKED,
      confidence: 'unverified',
      source: {
        url: 'https://theperfumespot.com/shipping-returns.html',
        quote: 'FREE SHIPPING ON ORDERS OVER $49*',
        readAt: CHECKED,
      },
      notes: 'Read from the banner on its shipping page; the asterisk\'s conditions and the rate below $49 were not found in the markup.',
    },
    taxNote: US_TAX_NOTE,
    checked:
      `${CHECKED}: robots.txt 200 at theperfumespot.com (www. redirects); xmlsitemap.php type=products page 1; a product page read, ` +
      "JSON-LD Product with priceCurrency USD and gtin14 (Le Sel d'Issey 3.4 oz EDP $59.98, 03423222119485).",
  },
  {
    id: 'dillards',
    name: "Dillard's",
    region: 'US',
    currency: 'USD',
    domain: 'www.dillards.com',
    homepage: 'https://www.dillards.com/',
    tiers: ['designer'],
    enabled: false,
    blockedReason:
      'Readable (robots.txt allows /p/, sitemap_beauty_1.xml lists about 1,700 fragrance pages, JSON-LD in USD), but each page holds every size in one AggregateOffer and states the size only inside checkoutPageURLTemplate; the shared JSON-LD reader returns one unsized listing a page (Lacoste L.12.12 Bleu EDP $106, read 2026-10-09). Needs a reader of its offers[] before it can be priced per bottle.',
    route: {
      kind: 'sitemap',
      sitemapRoute: {
        roots: ['https://www.dillards.com/sitemap/sitemap.xml'],
        follow: 'sitemap_beauty_\\d+\\.xml$',
        product: '^https://www\\.dillards\\.com/p/[^?#]*(?:eau-de-parfum|eau-de-toilette|parfum|cologne|perfume)[^?#]*/\\d+$',
        maxSitemaps: 3,
        requireGbp: true,
      },
    },
    minRequestGapMs: 2000,
    delivery: unverified('Not read.'),
    taxNote: US_TAX_NOTE,
    checked: `${CHECKED}: robots.txt 200 (493 B); sitemap read; a product page read.`,
  },
  {
    id: 'ecosmetics',
    name: 'eCosmetics',
    region: 'US',
    currency: 'USD',
    domain: 'www.ecosmetics.com',
    homepage: 'https://www.ecosmetics.com/',
    tiers: ['designer', 'niche'],
    enabled: false,
    blockedReason:
      "Its only route is WooCommerce's public Store API (robots.txt does not disallow /wp-json/), an application interface rather than a page, which round 2 flagged for the owner to rule on; and its variable products need one request per variation for a true price. Off until the owner rules.",
    route: null,
    minRequestGapMs: 2000,
    delivery: unverified('Not read.'),
    taxNote: US_TAX_NOTE,
    checked: '2026-10-09 (round 2): robots.txt 200 (226 B); Store API answers in USD, minor unit 2.',
  },
  {
    id: 'nordstrom',
    name: 'Nordstrom',
    region: 'US',
    currency: 'USD',
    domain: 'www.nordstrom.com',
    homepage: 'https://www.nordstrom.com/',
    tiers: ['designer', 'niche'],
    enabled: false,
    blockedReason:
      'Later, as the plan says: /api/ is disallowed by its robots.txt, /products.json is 404 and its pages are heavy (256 KB home). No route chosen yet.',
    route: null,
    minRequestGapMs: 2000,
    delivery: unverified('Not read.'),
    taxNote: US_TAX_NOTE,
    checked: '2026-10-09 (candidates pass): robots.txt 200 (2,685 B, /api/ disallowed); home 200; /products.json 404.',
  },
];
