/**
 * Turns the crawl output into the badge data the demo reads.
 *
 * Listings join to demo fragrances on EAN, which is the whole argument for
 * capturing GTINs during the crawl: matching on an exact identifier is free,
 * whereas matching "Dior Sauvage EDP 100ml" against "Sauvage Eau de Parfum
 * 3.4oz Dior" is the hardest problem in the project.
 *
 * Run after a crawl: npm run catalogue:demo
 */
import { readdirSync, existsSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CatalogueStore } from '../src/catalogue/store.js';
import { isNewListing } from '../src/catalogue/newBadge.js';
import { DEMO_FRAGRANCES } from '../demo/data.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dir = resolve(root, 'data/catalogue');

const byEan = new Map(DEMO_FRAGRANCES.map((f) => [f.ean, f.id]));
const store = new CatalogueStore(dir);
const now = new Date();

interface GenOffer {
  retailerId: string;
  price: number;
  wasPrice: number | null;
  promoEndsAt: string | null;
  stock: 'inStock' | 'outOfStock' | 'unknown';
  url: string;
  fetchedAt: string;
  firstSeenAt: string;
  isNew: boolean;
}

/** fragranceId -> every shop's current listing for it. */
const out: Record<string, GenOffer[]> = {};
let matched = 0;
let unmatched = 0;

if (existsSync(dir)) {
  for (const file of readdirSync(dir).filter((f) => f.endsWith('.json'))) {
    const snapshot = store.read(file.replace(/\.json$/, ''));

    for (const listing of snapshot.listings) {
      if (listing.status !== 'active') continue;

      const fragranceId = listing.ean ? byEan.get(listing.ean) : undefined;
      if (!fragranceId) {
        unmatched++;
        continue;
      }
      matched++;

      // A listing with no readable price cannot enter a price comparison.
      if (listing.priceGbp === null) {
        unmatched++;
        continue;
      }

      out[fragranceId] ??= [];
      out[fragranceId]!.push({
        retailerId: listing.retailerId,
        price: listing.priceGbp,
        wasPrice: listing.wasPriceGbp,
        promoEndsAt: listing.promoEndsAt,
        stock:
          listing.inStock === true ? 'inStock' : listing.inStock === false ? 'outOfStock' : 'unknown',
        url: listing.url,
        fetchedAt: listing.lastSeenAt,
        firstSeenAt: listing.firstSeenAt,
        isNew: isNewListing(listing, now),
      });
    }
  }
}

const body = `// Generated by scripts/build-demo-catalogue.ts. Do not edit by hand.
//
// Every price below came out of the catalogue crawl, joined to fragrances on
// EAN. Nothing here is typed by hand, so pointing the crawl at live shops with
// \`--source=live\` replaces these figures with real ones and no other code
// changes. The NEW badges are pipeline output for the same reason.
//
// Regenerate: npm run catalogue && npm run catalogue:demo

import type { RawOffer, StockState } from '../src/types/offer.js';

export interface CrawledOffer {
  retailerId: string;
  price: number;
  wasPrice: number | null;
  promoEndsAt: string | null;
  stock: StockState;
  url: string;
  fetchedAt: string;
  firstSeenAt: string;
  isNew: boolean;
}

export const CRAWLED: Record<string, CrawledOffer[]> =
${JSON.stringify(out, null, 2)};

/** When the crawl that produced this data ran. */
export const CRAWLED_AT = ${JSON.stringify(now.toISOString())};

/** Offers for one fragrance, in the shape the comparison core expects. */
export function offersFor(fragranceId: string): RawOffer[] {
  return (CRAWLED[fragranceId] ?? []).map((o) => ({
    retailerId: o.retailerId,
    variantId: fragranceId,
    price: o.price,
    wasPrice: o.wasPrice,
    currency: 'GBP' as const,
    stock: o.stock,
    url: o.url,
    promoEndsAt: o.promoEndsAt,
    fetchedAt: o.fetchedAt,
  }));
}

/** Whether a shop added this fragrance inside the badge window. */
export function isNewAt(fragranceId: string, retailerId: string): boolean {
  return CRAWLED[fragranceId]?.some((o) => o.retailerId === retailerId && o.isNew) ?? false;
}
`;

writeFileSync(resolve(root, 'demo/catalogue.generated.ts'), body);

const newCount = Object.values(out).flat().filter((f) => f.isNew).length;
console.log(
  `demo/catalogue.generated.ts written: ${matched} listings matched on EAN, ` +
    `${unmatched} unmatched, ${newCount} carrying the NEW badge`,
);
