// Generated by scripts/build-demo-catalogue.ts. Do not edit by hand.
//
// Every product and every price below was harvested from a live UK shop through
// its own sitemap. Nothing here is curated, invented or typed by hand: a
// fragrance appears because a shop was selling it when we looked.
//
// Regenerate: npm run harvest && npm run catalogue:demo

import type { RawOffer, StockState } from '../src/types/offer.js';

export interface CrawledOffer {
  retailerId: string;
  price: number;
  wasPrice: number | null;
  promoEndsAt: string | null;
  stock: StockState;
  url: string;
  fetchedAt: string;
  firstSeenAt: string;
  isNew: boolean;
}

export interface CatalogueEntry {
  id: string;
  brand: string;
  name: string;
  concentration: string;
  sizeMl: number;
  ean: string | null;
  shops: number;
}

/** Products, most widely stocked first. */
export const CATALOGUE: CatalogueEntry[] = [
  {
    "id": "justmylook-acq0032",
    "brand": "Acqua Di Parma",
    "name": "Blu Mediterraneo Bergamotto Di Calabria",
    "concentration": "Eau De Toilette",
    "sizeMl": 30,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-acq0053",
    "brand": "Acqua Di Parma",
    "name": "Colonia",
    "concentration": "Eau De Cologne",
    "sizeMl": 100,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-acq0049",
    "brand": "Acqua Di Parma",
    "name": "Blu Mediterraneo Mandorlo Di Sicilia",
    "concentration": "Eau De Toilette",
    "sizeMl": 150,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-acq0045",
    "brand": "Acqua Di Parma",
    "name": "Blu Mediterraneo Fico Di Amalfi",
    "concentration": "Eau De Toilette",
    "sizeMl": 150,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-acq0012",
    "brand": "Acqua Di Parma",
    "name": "Colonia Club",
    "concentration": "Eau De Cologne",
    "sizeMl": 180,
    "ean": null,
    "shops": 1
  },
  {
    "id": "ean-3616303322021",
    "brand": "Adidas",
    "name": "Pure Game",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "3616303322021",
    "shops": 1
  },
  {
    "id": "ean-3616303322052",
    "brand": "Adidas",
    "name": "Victory League",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "3616303322052",
    "shops": 1
  },
  {
    "id": "justmylook-afnn0006",
    "brand": "Afnan",
    "name": "Supremacy Not Only Intense Pour Homme",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-afnn0008",
    "brand": "Afnan",
    "name": "Supremacy Not Only Intense Pour Homme",
    "concentration": "Eau De Parfum",
    "sizeMl": 150,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-afnn0003",
    "brand": "Afnan",
    "name": "9pm Pour Homme",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-agen0002",
    "brand": "Agent Provocateur",
    "name": "Agent Provocateur Eau De Parfum 200ml",
    "concentration": "Eau De Parfum",
    "sizeMl": 200,
    "ean": null,
    "shops": 1
  },
  {
    "id": "ean-8411061411919",
    "brand": "Antonio Puig",
    "name": "Quorum",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "8411061411919",
    "shops": 1
  },
  {
    "id": "ean-022548006719",
    "brand": "Aramis",
    "name": "Aramis Eau de Toilette 110ml Spray",
    "concentration": "Eau De Toilette",
    "sizeMl": 110,
    "ean": "022548006719",
    "shops": 1
  },
  {
    "id": "justmylook-ar0003",
    "brand": "Aramis",
    "name": "Classic",
    "concentration": "Eau De Toilette",
    "sizeMl": 240,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-ari0012",
    "brand": "Ariana Grande",
    "name": "Thank U Next",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-ari0010",
    "brand": "Ariana Grande",
    "name": "Thank U Next",
    "concentration": "Eau De Parfum",
    "sizeMl": 30,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-ari0004",
    "brand": "Ariana Grande",
    "name": "Sweet Like Candy",
    "concentration": "Eau De Parfum",
    "sizeMl": 30,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-ari0015",
    "brand": "Ariana Grande",
    "name": "R.E.M.",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-ari0007",
    "brand": "Ariana Grande",
    "name": "Cloud",
    "concentration": "Eau De Parfum",
    "sizeMl": 30,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-arm0050",
    "brand": "Armaf",
    "name": "Club De Nuit Iconic",
    "concentration": "Eau De Parfum",
    "sizeMl": 105,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-arm0049",
    "brand": "Armaf",
    "name": "Club De Nuit Urban Man Elixir",
    "concentration": "Eau De Parfum",
    "sizeMl": 105,
    "ean": null,
    "shops": 1
  },
  {
    "id": "ean-3351500980406",
    "brand": "Azzaro",
    "name": "Azzaro Eau de Toilette 100ml Spray",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "3351500980406",
    "shops": 1
  },
  {
    "id": "justmylook-azz0020",
    "brand": "Azzaro",
    "name": "Wanted Girl",
    "concentration": "Eau De Parfum",
    "sizeMl": 80,
    "ean": null,
    "shops": 1
  },
  {
    "id": "justmylook-azz0018",
    "brand": "Azzaro",
    "name": "The Most Wanted",
    "concentration": "Parfum",
    "sizeMl": 50,
    "ean": null,
    "shops": 1
  },
  {
    "id": "ean-7640111497547",
    "brand": "Bentley",
    "name": "Intense",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": "7640111497547",
    "shops": 1
  },
  {
    "id": "ean-3577580202089",
    "brand": "Boucheron",
    "name": "Pour Homme",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": "3577580202089",
    "shops": 1
  },
  {
    "id": "ean-719346065405",
    "brand": "Britney Spears",
    "name": "Fantasy",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": "719346065405",
    "shops": 1
  },
  {
    "id": "ean-3614227748446",
    "brand": "Burberry",
    "name": "Weekend",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "3614227748446",
    "shops": 1
  },
  {
    "id": "ean-3616302020676",
    "brand": "Burberry",
    "name": "Goddess",
    "concentration": "Eau De Parfum",
    "sizeMl": 50,
    "ean": "3616302020676",
    "shops": 1
  },
  {
    "id": "ean-5045252667859",
    "brand": "Burberry",
    "name": "Brit",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": "5045252667859",
    "shops": 1
  },
  {
    "id": "ean-5045252667361",
    "brand": "Burberry",
    "name": "Burberry For Women Eau De Parfum 30ml Spray",
    "concentration": "Eau De Parfum",
    "sizeMl": 30,
    "ean": "5045252667361",
    "shops": 1
  },
  {
    "id": "ean-5045252667330",
    "brand": "Burberry",
    "name": "Burberry For Women Eau De Parfum 50ml Spray",
    "concentration": "Eau De Parfum",
    "sizeMl": 50,
    "ean": "5045252667330",
    "shops": 1
  },
  {
    "id": "ean-5045252667309",
    "brand": "Burberry",
    "name": "Burberry For Women Eau De Parfum 100ml Spray",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": "5045252667309",
    "shops": 1
  },
  {
    "id": "ean-5045252668214",
    "brand": "Burberry",
    "name": "London",
    "concentration": "Eau De Toilette",
    "sizeMl": 50,
    "ean": "5045252668214",
    "shops": 1
  },
  {
    "id": "ean-5045252668184",
    "brand": "Burberry",
    "name": "London",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "5045252668184",
    "shops": 1
  },
  {
    "id": "ean-5045252668085",
    "brand": "Burberry",
    "name": "London",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": "5045252668085",
    "shops": 1
  },
  {
    "id": "ean-5045294100406",
    "brand": "Burberry",
    "name": "Touch",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": "5045294100406",
    "shops": 1
  },
  {
    "id": "justmylook-burb0006",
    "brand": "Burberry",
    "name": "Brit",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": null,
    "shops": 1
  },
  {
    "id": "ean-3360370512044",
    "brand": "Cacharel",
    "name": "Anais Anais",
    "concentration": "Eau De Toilette",
    "sizeMl": 30,
    "ean": "3360370512044",
    "shops": 1
  },
  {
    "id": "ean-3360374533205",
    "brand": "Cacharel",
    "name": "Anais Anais",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "3360374533205",
    "shops": 1
  },
  {
    "id": "ean-3360373001774",
    "brand": "Cacharel",
    "name": "Cacharel Eau de Toilette 100ml Spray",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "3360373001774",
    "shops": 1
  },
  {
    "id": "ean-3360373048861",
    "brand": "Cacharel",
    "name": "Eden",
    "concentration": "Eau De Parfum",
    "sizeMl": 30,
    "ean": "3360373048861",
    "shops": 1
  },
  {
    "id": "ean-3360373000081",
    "brand": "Cacharel",
    "name": "Loulou",
    "concentration": "Eau De Parfum",
    "sizeMl": 50,
    "ean": "3360373000081",
    "shops": 1
  },
  {
    "id": "ean-3360373016334",
    "brand": "Cacharel",
    "name": "Noa",
    "concentration": "Eau De Toilette",
    "sizeMl": 30,
    "ean": "3360373016334",
    "shops": 1
  },
  {
    "id": "ean-3360373016358",
    "brand": "Cacharel",
    "name": "Noa",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "3360373016358",
    "shops": 1
  },
  {
    "id": "ean-088300606511",
    "brand": "Calvin Klein",
    "name": "Obsession",
    "concentration": "Eau De Toilette",
    "sizeMl": 125,
    "ean": "088300606511",
    "shops": 1
  },
  {
    "id": "ean-088300606535",
    "brand": "Calvin Klein",
    "name": "Obsession",
    "concentration": "Aftershave",
    "sizeMl": 125,
    "ean": "088300606535",
    "shops": 1
  },
  {
    "id": "ean-088300602513",
    "brand": "Calvin Klein",
    "name": "Contradiction",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": "088300602513",
    "shops": 1
  },
  {
    "id": "ean-088300608409",
    "brand": "Calvin Klein",
    "name": "Escape",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": "088300608409",
    "shops": 1
  },
  {
    "id": "ean-088300100514",
    "brand": "Calvin Klein",
    "name": "Escape",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "088300100514",
    "shops": 1
  },
  {
    "id": "ean-3607342107977",
    "brand": "Calvin Klein",
    "name": "Aqua Eternity",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "3607342107977",
    "shops": 1
  },
  {
    "id": "ean-0088300104437",
    "brand": "Calvin Klein",
    "name": "Be",
    "concentration": "Eau De Toilette",
    "sizeMl": 200,
    "ean": "0088300104437",
    "shops": 1
  },
  {
    "id": "ean-3607342058057",
    "brand": "Calvin Klein",
    "name": "CK Free",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "3607342058057",
    "shops": 1
  },
  {
    "id": "ean-088300607402",
    "brand": "Calvin Klein",
    "name": "One",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "088300607402",
    "shops": 1
  },
  {
    "id": "ean-088300607433",
    "brand": "Calvin Klein",
    "name": "One",
    "concentration": "Eau De Toilette",
    "sizeMl": 200,
    "ean": "088300607433",
    "shops": 1
  },
  {
    "id": "ean-3607342401860",
    "brand": "Calvin Klein",
    "name": "One Shock Her",
    "concentration": "Eau De Toilette",
    "sizeMl": 200,
    "ean": "3607342401860",
    "shops": 1
  },
  {
    "id": "ean-088300000319",
    "brand": "Calvin Klein",
    "name": "Contradiction",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "088300000319",
    "shops": 1
  },
  {
    "id": "ean-5050456006472",
    "brand": "Cerruti",
    "name": "Vivo Homme",
    "concentration": "Eau De Parfum",
    "sizeMl": 60,
    "ean": "5050456006472",
    "shops": 1
  },
  {
    "id": "ean-3139420225018",
    "brand": "Dunhill London",
    "name": "Desire Red",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "3139420225018",
    "shops": 1
  },
  {
    "id": "ean-4035773552513",
    "brand": "Dunhill London",
    "name": "Edition",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "4035773552513",
    "shops": 1
  },
  {
    "id": "ean-3274870303166",
    "brand": "Givenchy",
    "name": "Pour Homme",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": "3274870303166",
    "shops": 1
  },
  {
    "id": "ean-737052057989",
    "brand": "HUGO BOSS",
    "name": "BOSS Woman",
    "concentration": "Eau De Parfum",
    "sizeMl": 90,
    "ean": "737052057989",
    "shops": 1
  },
  {
    "id": "ean-737052351155",
    "brand": "HUGO BOSS",
    "name": "BOSS Bottled",
    "concentration": "Aftershave",
    "sizeMl": 50,
    "ean": "737052351155",
    "shops": 1
  },
  {
    "id": "ean-3414206000615",
    "brand": "JOOP!",
    "name": "Homme",
    "concentration": "Aftershave",
    "sizeMl": 75,
    "ean": "3414206000615",
    "shops": 1
  },
  {
    "id": "ean-3274872404113",
    "brand": "Kenzo",
    "name": "Flower by Kenzo",
    "concentration": "Eau De Parfum",
    "sizeMl": 30,
    "ean": "3274872404113",
    "shops": 1
  },
  {
    "id": "ean-3616302931781",
    "brand": "Lacoste",
    "name": "Red Pour Homme",
    "concentration": "Eau De Toilette",
    "sizeMl": 125,
    "ean": "3616302931781",
    "shops": 1
  },
  {
    "id": "lookfantastic-10002885",
    "brand": "Unbranded",
    "name": "Juicy Couture",
    "concentration": "Eau De Parfum",
    "sizeMl": 50,
    "ean": null,
    "shops": 1
  },
  {
    "id": "lookfantastic-10002886",
    "brand": "Unbranded",
    "name": "Juicy Couture",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": null,
    "shops": 1
  },
  {
    "id": "lookfantastic-10077798",
    "brand": "Unbranded",
    "name": "Diesel Only The Brave",
    "concentration": "Eau De Toilette",
    "sizeMl": 50,
    "ean": null,
    "shops": 1
  },
  {
    "id": "lookfantastic-10301201",
    "brand": "Unbranded",
    "name": "Acqua Di Parma Magnolia Nobile",
    "concentration": "Eau De Parfum",
    "sizeMl": 50,
    "ean": null,
    "shops": 1
  },
  {
    "id": "lookfantastic-10588308",
    "brand": "Unbranded",
    "name": "Menaji Power Hydrator with Hyaluronic Acid (4oz./)",
    "concentration": "Aftershave",
    "sizeMl": 118,
    "ean": null,
    "shops": 1
  },
  {
    "id": "lookfantastic-10810788",
    "brand": "Unbranded",
    "name": "Juicy Couture Viva Noir",
    "concentration": "Eau De Parfum",
    "sizeMl": 50,
    "ean": null,
    "shops": 1
  },
  {
    "id": "lookfantastic-10952559",
    "brand": "Unbranded",
    "name": "Rabanne Invictus",
    "concentration": "Eau De Toilette",
    "sizeMl": 100,
    "ean": null,
    "shops": 1
  },
  {
    "id": "lookfantastic-10954663",
    "brand": "Unbranded",
    "name": "DKNY Be Delicious",
    "concentration": "Eau De Parfum",
    "sizeMl": 100,
    "ean": null,
    "shops": 1
  }
];

export const CRAWLED: Record<string, CrawledOffer[]> = {
  "justmylook-acq0032": [
    {
      "retailerId": "justmylook",
      "price": 34.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.justmylook.com/products/acqua-di-parma-blu-mediterraneo-bergamotto-di-calabria-eau-de-toilette-30ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-acq0053": [
    {
      "retailerId": "justmylook",
      "price": 70.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.justmylook.com/products/acqua-di-parma-colonia-eau-de-cologne-100ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-acq0049": [
    {
      "retailerId": "justmylook",
      "price": 101.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.justmylook.com/products/acqua-di-parma-blu-mediterraneo-mandorlo-di-sicilia-eau-de-toilette-150ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-acq0045": [
    {
      "retailerId": "justmylook",
      "price": 86.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.justmylook.com/products/acqua-di-parma-blu-mediterraneo-fico-di-amalfi-eau-de-toilette-150ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-acq0012": [
    {
      "retailerId": "justmylook",
      "price": 87.95,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.justmylook.com/products/acqua-di-parma-colonia-club-eau-de-cologne-180ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3616303322021": [
    {
      "retailerId": "beautybase",
      "price": 6.95,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/pure-game-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3616303322052": [
    {
      "retailerId": "beautybase",
      "price": 6.95,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/adidas-victory-league-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-afnn0006": [
    {
      "retailerId": "justmylook",
      "price": 35.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.justmylook.com/products/afnan-supremacy-not-only-intense-pour-homme-eau-de-parfum-100ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-afnn0008": [
    {
      "retailerId": "justmylook",
      "price": 41.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.justmylook.com/products/afnan-supremacy-not-only-intense-pour-homme-eau-de-parfum-150ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-afnn0003": [
    {
      "retailerId": "justmylook",
      "price": 22.5,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.justmylook.com/products/afnan-9pm-pour-homme-eau-de-parfum-100ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-agen0002": [
    {
      "retailerId": "justmylook",
      "price": 25.99,
      "wasPrice": null,
      "promoEndsAt": "2027-08-01T00:00:00.000Z",
      "stock": "inStock",
      "url": "https://www.justmylook.com/products/agent-provocateur-eau-de-parfum-200ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-8411061411919": [
    {
      "retailerId": "beautybase",
      "price": 14,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/quorum-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-022548006719": [
    {
      "retailerId": "beautybase",
      "price": 21.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/aramis-eau-de-toilette-110ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-ar0003": [
    {
      "retailerId": "justmylook",
      "price": 43.99,
      "wasPrice": null,
      "promoEndsAt": "2027-08-01T00:00:00.000Z",
      "stock": "outOfStock",
      "url": "https://www.justmylook.com/products/aramis-classic-eau-de-toilette-240ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-ari0012": [
    {
      "retailerId": "justmylook",
      "price": 40.5,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.justmylook.com/products/ariana-grande-thank-u-next-eau-de-parfum-100ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-ari0010": [
    {
      "retailerId": "justmylook",
      "price": 27.95,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.justmylook.com/products/ariana-grande-thank-u-next-eau-de-parfum-30ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-ari0004": [
    {
      "retailerId": "justmylook",
      "price": 26.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.justmylook.com/products/ariana-grande-sweet-like-candy-eau-de-parfum-30ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-ari0015": [
    {
      "retailerId": "justmylook",
      "price": 35.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.justmylook.com/products/ariana-grande-r-e-m-eau-de-parfum-100ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-ari0007": [
    {
      "retailerId": "justmylook",
      "price": 27.95,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.justmylook.com/products/ariana-grande-cloud-eau-de-parfum-30ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-arm0050": [
    {
      "retailerId": "justmylook",
      "price": 31.5,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.justmylook.com/products/armaf-club-de-nuit-iconic-eau-de-parfum-105ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-arm0049": [
    {
      "retailerId": "justmylook",
      "price": 27.49,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.justmylook.com/products/armaf-club-de-nuit-urban-man-elixir-eau-de-parfum-105ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3351500980406": [
    {
      "retailerId": "beautybase",
      "price": 39.95,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/azzaro-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-azz0020": [
    {
      "retailerId": "justmylook",
      "price": 59.8,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.justmylook.com/products/azzaro-wanted-girl-eau-de-parfum-80ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-azz0018": [
    {
      "retailerId": "justmylook",
      "price": 39.95,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.justmylook.com/products/azzaro-the-most-wanted-parfum-50ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-7640111497547": [
    {
      "retailerId": "beautybase",
      "price": 35,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/bentley-for-men-intense-eau-de-parfum-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3577580202089": [
    {
      "retailerId": "beautybase",
      "price": 42,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/boucheron-ph-eau-de-parfum-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-719346065405": [
    {
      "retailerId": "beautybase",
      "price": 18.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/fantasy-eau-de-parfum-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3614227748446": [
    {
      "retailerId": "allbeauty",
      "price": 31.6,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/products/p-burberry-weekend-for-men-eau-de-toilette-spray-100ml-12044984",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3616302020676": [
    {
      "retailerId": "beautybase",
      "price": 75,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.beautybase.com/products/burberry-goddess-eau-de-parfum-50ml-refillable-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-5045252667859": [
    {
      "retailerId": "beautybase",
      "price": 50,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.beautybase.com/products/burberry-brit-for-women-eau-de-parfum-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-5045252667361": [
    {
      "retailerId": "beautybase",
      "price": 33,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/burberry-for-women-eau-de-parfum-30ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-5045252667330": [
    {
      "retailerId": "beautybase",
      "price": 35,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/burberry-for-women-eau-de-parfum-50ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-5045252667309": [
    {
      "retailerId": "beautybase",
      "price": 45,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/burberry-for-women-eau-de-parfum-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-5045252668214": [
    {
      "retailerId": "beautybase",
      "price": 25,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/burberry-london-for-men-eau-de-toilette-50ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-5045252668184": [
    {
      "retailerId": "beautybase",
      "price": 35,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/burberry-london-for-men-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-5045252668085": [
    {
      "retailerId": "beautybase",
      "price": 45,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/burberry-london-for-women-eau-de-parfum-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-5045294100406": [
    {
      "retailerId": "beautybase",
      "price": 40,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/burberry-touch-for-women-eau-de-parfum-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "justmylook-burb0006": [
    {
      "retailerId": "justmylook",
      "price": 38.5,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.justmylook.com/products/burberry-brit-for-her-eau-de-parfum-100ml",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3360370512044": [
    {
      "retailerId": "beautybase",
      "price": 22.95,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.beautybase.com/products/anais-anais-eau-de-toilette-30ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3360374533205": [
    {
      "retailerId": "beautybase",
      "price": 29.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/anais-anais-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3360373001774": [
    {
      "retailerId": "beautybase",
      "price": 39.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/cacharel-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3360373048861": [
    {
      "retailerId": "beautybase",
      "price": 19.95,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.beautybase.com/products/eden-eau-de-parfum-30ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3360373000081": [
    {
      "retailerId": "beautybase",
      "price": 35,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/loulou-eau-de-parfum-50ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3360373016334": [
    {
      "retailerId": "beautybase",
      "price": 19.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/noa-eau-de-toilette-30ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3360373016358": [
    {
      "retailerId": "beautybase",
      "price": 39.95,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/noa-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-088300606511": [
    {
      "retailerId": "allbeauty",
      "price": 19.95,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/products/p-calvin-klein-obsession-for-men-eau-de-toilette-125ml-11079263",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-088300606535": [
    {
      "retailerId": "allbeauty",
      "price": 18.9,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/products/p-calvin-klein-obsession-for-men-aftershave-splash-125ml-14575846",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-088300602513": [
    {
      "retailerId": "allbeauty",
      "price": 25.9,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/products/p-calvin-klein-contradiction-eau-de-parfum-100ml-14271183",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-088300608409": [
    {
      "retailerId": "allbeauty",
      "price": 24.5,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/products/p-calvin-klein-escape-eau-de-parfum-100ml-17823521",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-088300100514": [
    {
      "retailerId": "allbeauty",
      "price": 20.3,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/products/p-calvin-klein-escape-for-men-eau-de-toilette-100ml-11210240",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3607342107977": [
    {
      "retailerId": "beautybase",
      "price": 25,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/aqua-eternity-for-men-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-0088300104437": [
    {
      "retailerId": "beautybase",
      "price": 29,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/ck-be-eau-de-toilette-200ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3607342058057": [
    {
      "retailerId": "beautybase",
      "price": 19.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/ck-free-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-088300607402": [
    {
      "retailerId": "beautybase",
      "price": 25,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/ck-one-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-088300607433": [
    {
      "retailerId": "beautybase",
      "price": 35,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/ck-one-eau-de-toilette-200ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3607342401860": [
    {
      "retailerId": "beautybase",
      "price": 29.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/ck-one-shock-her-eau-de-toilette-200ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-088300000319": [
    {
      "retailerId": "beautybase",
      "price": 22,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/contradiction-for-men-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-5050456006472": [
    {
      "retailerId": "beautybase",
      "price": 49.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/cerruti-vivo-homme-eau-de-parfum-60ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3139420225018": [
    {
      "retailerId": "beautybase",
      "price": 39.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.beautybase.com/products/dunhill-london-desire-red-for-men-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-4035773552513": [
    {
      "retailerId": "beautybase",
      "price": 45,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.beautybase.com/products/dunhill-london-edition-eau-de-toilette-100ml-spray",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3274870303166": [
    {
      "retailerId": "allbeauty",
      "price": 36.4,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/products/p-givenchy-pour-homme-eau-de-toilette-spray-100ml-14574780",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-737052057989": [
    {
      "retailerId": "allbeauty",
      "price": 33.2,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/products/p-hugo-boss-boss-woman-eau-de-parfum-90ml-10076083",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-737052351155": [
    {
      "retailerId": "allbeauty",
      "price": 41.5,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/products/p-hugo-boss-boss-bottled-aftershave-splash-50ml-11858151",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3414206000615": [
    {
      "retailerId": "allbeauty",
      "price": 14.8,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/products/p-joop-homme-aftershave-splash-75ml-10002651",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3274872404113": [
    {
      "retailerId": "allbeauty",
      "price": 27.95,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/products/p-kenzo-flower-by-kenzo-eau-de-parfum-spray-30ml-14574936",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "ean-3616302931781": [
    {
      "retailerId": "allbeauty",
      "price": 28.5,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/products/p-lacoste-red-pour-homme-eau-de-toilette-spray-125ml-14574870",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "lookfantastic-10002885": [
    {
      "retailerId": "lookfantastic",
      "price": 44.25,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.lookfantastic.com/p/juicy-couture-eau-de-parfum-50ml/10002885/",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "lookfantastic-10002886": [
    {
      "retailerId": "lookfantastic",
      "price": 59.25,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.lookfantastic.com/p/juicy-couture-eau-de-parfum-spray-100ml/10002886/",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "lookfantastic-10077798": [
    {
      "retailerId": "lookfantastic",
      "price": 60,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.lookfantastic.com/p/diesel-only-the-brave-eau-de-toilette-50ml/10077798/",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "lookfantastic-10301201": [
    {
      "retailerId": "lookfantastic",
      "price": 180,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.lookfantastic.com/p/acqua-di-parma-magnolia-nobile-eau-de-parfum-50ml/10301201/",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "lookfantastic-10588308": [
    {
      "retailerId": "lookfantastic",
      "price": 24,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://www.lookfantastic.com/p/menaji-power-hydrator-aftershave-with-hyaluronic-acid-4oz.-118ml/10588308/",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "lookfantastic-10810788": [
    {
      "retailerId": "lookfantastic",
      "price": 44.25,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.lookfantastic.com/p/juicy-couture-viva-noir-eau-de-parfum-50ml/10810788/",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "lookfantastic-10952559": [
    {
      "retailerId": "lookfantastic",
      "price": 71.25,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.lookfantastic.com/p/paco-rabanne-invictus-eau-de-toilette-100ml/10952559/",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ],
  "lookfantastic-10954663": [
    {
      "retailerId": "lookfantastic",
      "price": 77,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://www.lookfantastic.com/p/dkny-be-delicious-eau-de-parfum-100ml/10954663/",
      "fetchedAt": "2026-08-01T21:32:03.579Z",
      "firstSeenAt": "2026-08-01T21:32:03.579Z",
      "isNew": false
    }
  ]
};

/** When the harvest that produced this data ran. */
export const CRAWLED_AT = "2026-08-01T21:32:03.579Z";

/** How many shops the data came from. */
export const SHOP_COUNT = 4;

export function offersFor(productId: string): RawOffer[] {
  return (CRAWLED[productId] ?? []).map((o) => ({
    retailerId: o.retailerId,
    variantId: productId,
    price: o.price,
    wasPrice: o.wasPrice,
    currency: 'GBP' as const,
    stock: o.stock,
    url: o.url,
    promoEndsAt: o.promoEndsAt,
    fetchedAt: o.fetchedAt,
  }));
}

/** Whether a shop added this product inside the badge window. */
export function isNewAt(productId: string, retailerId: string): boolean {
  return CRAWLED[productId]?.some((o) => o.retailerId === retailerId && o.isNew) ?? false;
}
