// Generated by scripts/build-demo-catalogue.ts. Do not edit by hand.
//
// Every price below came out of the catalogue crawl, joined to fragrances on
// EAN. Nothing here is typed by hand, so pointing the crawl at live shops with
// `--source=live` replaces these figures with real ones and no other code
// changes. The NEW badges are pipeline output for the same reason.
//
// Regenerate: npm run catalogue && npm run catalogue:demo

import type { RawOffer, StockState } from '../src/types/offer.js';

export interface CrawledOffer {
  retailerId: string;
  price: number;
  wasPrice: number | null;
  promoEndsAt: string | null;
  stock: StockState;
  url: string;
  fetchedAt: string;
  firstSeenAt: string;
  isNew: boolean;
}

export const CRAWLED: Record<string, CrawledOffer[]> =
{
  "bleu-edp-100": [
    {
      "retailerId": "allbeauty",
      "price": 91.75,
      "wasPrice": 99,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/p/ab-bleu-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "boots",
      "price": 105,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://boots.com/p/10255901",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "notino-uk",
      "price": 99.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://notino.co.uk/p/ntn-bleu-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "the-fragrance-shop",
      "price": 88.4,
      "wasPrice": 110,
      "promoEndsAt": "2026-08-04T06:21:28.909Z",
      "stock": "inStock",
      "url": "https://thefragranceshop.co.uk/p/tfs-bleu-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    }
  ],
  "aventus-100": [
    {
      "retailerId": "allbeauty",
      "price": 295.5,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/p/ab-aventus-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "notino-uk",
      "price": 284,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://notino.co.uk/p/ntn-aventus-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "selfridges",
      "price": 335,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://selfridges.com/p/sf-aventus-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    }
  ],
  "acqua-profumo-75": [
    {
      "retailerId": "allbeauty",
      "price": 71.5,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/p/ab-acqua-75",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "boots",
      "price": 82,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://boots.com/p/10233190",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "notino-uk",
      "price": 69.9,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://notino.co.uk/p/ntn-acqua-75",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    }
  ],
  "khamrah-100": [
    {
      "retailerId": "allbeauty",
      "price": 23.45,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/p/ab-khamrah-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "notino-uk",
      "price": 21.9,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://notino.co.uk/p/ntn-khamrah-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "the-fragrance-shop",
      "price": 24.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://thefragranceshop.co.uk/p/tfs-khamrah-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    }
  ],
  "baccarat-540-70": [
    {
      "retailerId": "allbeauty",
      "price": 232.5,
      "wasPrice": 255,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://allbeauty.com/p/ab-baccarat-70",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-08-01T16:21:41.463Z",
      "isNew": true
    },
    {
      "retailerId": "notino-uk",
      "price": 219,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://notino.co.uk/p/ntn-baccarat-70",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-08-01T16:21:41.463Z",
      "isNew": true
    },
    {
      "retailerId": "selfridges",
      "price": 245,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://selfridges.com/p/sf-baccarat-70",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    }
  ],
  "sauvage-edp-100": [
    {
      "retailerId": "boots",
      "price": 24.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://boots.com/p/10255432",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "notino-uk",
      "price": 23.9,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://notino.co.uk/p/ntn-sauvage-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "superdrug",
      "price": 25.5,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://superdrug.com/p/sd-sauvage-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    }
  ],
  "one-million-100": [
    {
      "retailerId": "boots",
      "price": 62,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://boots.com/p/10261188",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "superdrug",
      "price": 59.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://superdrug.com/p/sd-million-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "the-fragrance-shop",
      "price": 55,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://thefragranceshop.co.uk/p/tfs-million-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    }
  ],
  "libre-edp-90": [
    {
      "retailerId": "boots",
      "price": 78,
      "wasPrice": 92,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://boots.com/p/10277431",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    },
    {
      "retailerId": "superdrug",
      "price": 23.75,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://superdrug.com/p/sd-libre-90",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    }
  ],
  "eros-edt-100": [
    {
      "retailerId": "boots",
      "price": 55,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://boots.com/p/10299874",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-08-01T16:21:41.463Z",
      "isNew": true
    },
    {
      "retailerId": "notino-uk",
      "price": 44.9,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://notino.co.uk/p/ntn-eros-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-08-01T16:21:41.463Z",
      "isNew": true
    },
    {
      "retailerId": "superdrug",
      "price": 49.99,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "inStock",
      "url": "https://superdrug.com/p/sd-eros-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-08-01T16:21:41.463Z",
      "isNew": true
    },
    {
      "retailerId": "the-fragrance-shop",
      "price": 42.5,
      "wasPrice": 78,
      "promoEndsAt": "2026-08-02T11:21:28.909Z",
      "stock": "inStock",
      "url": "https://thefragranceshop.co.uk/p/tfs-eros-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    }
  ],
  "wood-sage-100": [
    {
      "retailerId": "selfridges",
      "price": 112,
      "wasPrice": null,
      "promoEndsAt": null,
      "stock": "outOfStock",
      "url": "https://selfridges.com/p/sf-woodsage-100",
      "fetchedAt": "2026-08-01T16:21:41.463Z",
      "firstSeenAt": "2026-07-31T06:00:00.000Z",
      "isNew": false
    }
  ]
};

/** When the crawl that produced this data ran. */
export const CRAWLED_AT = "2026-08-01T16:22:18.432Z";

/** Offers for one fragrance, in the shape the comparison core expects. */
export function offersFor(fragranceId: string): RawOffer[] {
  return (CRAWLED[fragranceId] ?? []).map((o) => ({
    retailerId: o.retailerId,
    variantId: fragranceId,
    price: o.price,
    wasPrice: o.wasPrice,
    currency: 'GBP' as const,
    stock: o.stock,
    url: o.url,
    promoEndsAt: o.promoEndsAt,
    fetchedAt: o.fetchedAt,
  }));
}

/** Whether a shop added this fragrance inside the badge window. */
export function isNewAt(fragranceId: string, retailerId: string): boolean {
  return CRAWLED[fragranceId]?.some((o) => o.retailerId === retailerId && o.isNew) ?? false;
}
