// Generated by scripts/testCountReporter.ts as a side effect of every
// non-watch `vitest run` — see that file's header comment for why. Do not
// edit by hand: it is overwritten the next time anyone runs the suite,
// whether that is `npm test`, `npx vitest run`, or CI's own test step
// before every crawl.

/** How many tests vitest collected the last time the full suite ran. */
export const TEST_COUNT = 1574;
