import {
  fragranceBaseKey,
  fragranceLinkKey,
  fragranticaPath,
  fragranticaUrlFromPath,
  type MatchQuality,
} from './fragranceLinkMatch.js';

/**
 * The committed record of which page on Fragrantica, and which page on the
 * brand's own site, is each perfume's — data/fragrance-links.json — and the
 * compact form of it the demo ships (demo/fragranceLinks.generated.ts).
 *
 * Both are written by scripts/resolve-fragrance-links.ts and nothing else.
 * This module is the part of that which is worth testing without a network:
 * the shapes, the compaction, and the lookup the demo does at render time.
 */

export type FragranticaMethod = 'bing-search' | 'bing-seen';
export type OfficialMethod = 'house-storefront' | 'brand-storefront-offer' | 'sitemap' | 'bing-search';

export interface LinkEntry {
  /** https://www.fragrantica.com/perfume/<Brand>/<Name>-<id>.html, only when checked. */
  fragrantica?: string;
  fragranticaMatch?: MatchQuality;
  /** A page on the brand's own domain naming this perfume, only when checked. */
  official?: string;
  officialMatch?: MatchQuality;
  /** When anything about this entry last changed or was last attempted. */
  checkedAt: string;
  /** What found each link. */
  method: { fragrantica?: FragranticaMethod; official?: OfficialMethod };
  /**
   * When each source was last *attempted*, hits and misses alike, so a rerun
   * does not repeat a search that already came back empty.
   */
  tried?: { fragrantica?: string; official?: string };
}

export interface LinksFile {
  version: 1;
  generatedAt: string;
  entries: Record<string, LinkEntry>;
}

/** [Fragrantica "Folder/Slug-id", official URL]; an empty string is "none". */
export type CompactLinks = readonly [string, string];
export type CompactTable = Readonly<Record<string, CompactLinks>>;

/**
 * Flatten the file into what the page needs. Every entry with a link is
 * keyed brand|name|concentration. A brand|name key is added as well, but only
 * from links whose page does not state a concentration ("base" matches): such
 * a page is right for every concentration of that perfume, so a variant the
 * file has no entry of its own for can still use it.
 */
export function compactTable(entries: Readonly<Record<string, LinkEntry>>): Record<string, CompactLinks> {
  const table: Record<string, CompactLinks> = {};
  const base: Record<string, [string, string]> = {};
  for (const key of Object.keys(entries).sort()) {
    const e = entries[key]!;
    const f = e.fragrantica ? (fragranticaPath(e.fragrantica) ?? '') : '';
    const o = e.official ?? '';
    if (!f && !o) continue;
    table[key] = [f, o];
    const parts = key.split('|');
    const baseKey = `${parts[0]}|${parts[1]}`;
    const slot = (base[baseKey] ??= ['', '']);
    if (f && e.fragranticaMatch === 'base' && !slot[0]) slot[0] = f;
    if (o && e.officialMatch === 'base' && !slot[1]) slot[1] = o;
  }
  for (const [k, v] of Object.entries(base)) if (v[0] || v[1]) table[k] = v;
  return table;
}

export interface ResolvedLinks {
  fragrantica: string | null;
  official: string | null;
}

/** What the page should link to for one product, from a compact table. Null where nothing is stored. */
export function lookupLinks(
  table: CompactTable,
  brand: string,
  name: string,
  concentration: string,
): ResolvedLinks {
  const own = table[fragranceLinkKey(brand, name, concentration)];
  const base = table[fragranceBaseKey(brand, name)];
  const f = own?.[0] || base?.[0] || '';
  const o = own?.[1] || base?.[1] || '';
  return { fragrantica: f ? fragranticaUrlFromPath(f) : null, official: o || null };
}

/** The TypeScript the demo bundle reads. JSON-valid on purpose: scripts/bundle-demo.ts moves such literals out of the JS. */
export function renderGeneratedModule(table: Readonly<Record<string, CompactLinks>>, generatedAt: string): string {
  const lines = Object.keys(table)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(table[k])}`);
  return [
    '// Generated by scripts/resolve-fragrance-links.ts from data/fragrance-links.json. Do not edit by hand.',
    '//',
    '// Each value is [Fragrantica "Folder/Slug-id" (https://www.fragrantica.com/perfume/<it>.html), the',
    "// brand's own page for that perfume]. An empty string means none was found and checked; the page then",
    "// falls back to the brand's homepage / a Fragrantica search. See demo/fragranceLinks.ts.",
    '//',
    '// Regenerate: npm run links:resolve',
    '',
    `export const FRAGRANCE_LINKS_AT = ${JSON.stringify(generatedAt)};`,
    '',
    'export const FRAGRANCE_LINKS: Record<string, readonly [string, string]> = {',
    lines.join(',\n'),
    '};',
    '',
  ].join('\n');
}

/** One entry per line, so a rerun's diff shows the perfumes that changed and nothing else. */
export function renderLinksFile(file: LinksFile): string {
  const keys = Object.keys(file.entries).sort();
  const body = keys.map((k) => `${JSON.stringify(k)}:${JSON.stringify(file.entries[k])}`).join(',\n');
  return `{"version":${file.version},"generatedAt":${JSON.stringify(file.generatedAt)},"entries":{\n${body}\n}}\n`;
}
